apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: Project to configure argocd self-manage application
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/manishyadav618/DemoRepo2.git
  roles:
    - name: read-sync
      description: Read and Sync Privileges
      policies:
        - p , proj:argocd:read-sync, applications, get, argocd/*, allow
        - p , proj:argocd:read-sync, applications, sync, argocd/*, allow
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'


